name: Deploy to Server

on:
  push:
    branches:
      - main  # Change to your branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH Host Key
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p 2245 your_server_ip >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        ssh -p 2245 root@13.234.175.14 "cd /home/lodhaadmindigita/public_html && git pull origin main"
